[profile.default]
src = "src"
out = "out"
libs = ["lib"]

# Compiler & Optimization Settings
viaIR = false                          # disable for smaller bytecode
ffi = true
evm_version = "cancun"
optimizer = true                       # enable optimizer
optimizer_runs = 20000                 # higher runs = smaller deployment bytecode
fs_permissions = [{ access = "read", path = "./"}]

# Import remappings
remappings = [
  "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
  "@chainlink/contracts/=lib/chainlink-brownie-contracts/contracts/src/"
]

# Allow large contract sets by default
bytecode_hash = "none"

# Etherscan-style explorer configuration (for Basescan)
[etherscan]
84532 = { key = "${VERIFIER_API_KEY}", url = "https://api-sepolia.basescan.org/api" }

# (optional) default RPC URL for local scripts
[rpc_endpoints]
base_sepolia = "${RPC_URL}"
